
//
// This file has been generated by the Cornerstone file generator.
//
// PLEASE, DO NOT EDIT IT MANUALLY
//

#pragma once

#include "CoreMinimal.h"
#include "Conduit.h"
#include "GenUtils.h"
#include "RpcClient.h"
#include "VizorDemonstration.generated.h"


// Enums:
// Structures:
USTRUCT(BlueprintType, meta=(DisplayName="VizorDemonstration HelloRequest"))
struct FVizorDemonstration_HelloRequest
{
    GENERATED_USTRUCT_BODY()

public:
    // Conduits and GRPC stub
    UPROPERTY(BlueprintReadWrite, Transient)
    FString Name;
};

USTRUCT(BlueprintType, meta=(DisplayName="VizorDemonstration HelloResponse"))
struct FVizorDemonstration_HelloResponse
{
    GENERATED_USTRUCT_BODY()

public:
    // Conduits and GRPC stub
    UPROPERTY(BlueprintReadWrite, Transient)
    FString Message;
};

USTRUCT(BlueprintType, meta=(DisplayName="VizorDemonstration ServerTimeRequest"))
struct FVizorDemonstration_ServerTimeRequest
{
    GENERATED_USTRUCT_BODY()
};

USTRUCT(BlueprintType, meta=(DisplayName="VizorDemonstration ServerTimeResponse"))
struct FVizorDemonstration_ServerTimeResponse
{
    GENERATED_USTRUCT_BODY()

public:
    // Conduits and GRPC stub
    UPROPERTY(BlueprintReadWrite, Transient)
    int64 UnixTimeStamp;

    UPROPERTY(BlueprintReadWrite, Transient)
    int32 Hours;

    UPROPERTY(BlueprintReadWrite, Transient)
    int32 Minutes;

    UPROPERTY(BlueprintReadWrite, Transient)
    int32 Seconds;

    UPROPERTY(BlueprintReadWrite, Transient)
    FString Timezone;

    UPROPERTY(BlueprintReadWrite, Transient)
    FString Location;
};

// Forward class definitions (for delegates)
class UHelloServiceRpcClient;

// Dispatcher delegates
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FEventHelloHelloService, UHelloServiceRpcClient*, RpcClient, const FVizorDemonstration_HelloResponse&, Response, FGrpcStatus, Status);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FEventServerTimeHelloService, UHelloServiceRpcClient*, RpcClient, const FVizorDemonstration_ServerTimeResponse&, Response, FGrpcStatus, Status);


UCLASS()
class UHelloServiceRpcClient : public URpcClient
{
    GENERATED_BODY()

public:
    // Conduits and GRPC stub
    TConduit<TRequestWithContext<FVizorDemonstration_HelloRequest>, TResponseWithStatus<FVizorDemonstration_HelloResponse>> HelloConduit;

    TConduit<TRequestWithContext<FVizorDemonstration_ServerTimeRequest>, TResponseWithStatus<FVizorDemonstration_ServerTimeResponse>> ServerTimeConduit;

    UPROPERTY(BlueprintAssignable, Category="Vizor|RPC Responses|HelloService")
    FEventHelloHelloService EventHello;

    UPROPERTY(BlueprintAssignable, Category="Vizor|RPC Responses|HelloService")
    FEventServerTimeHelloService EventServerTime;


    // Methods
    void HierarchicalInit() override;

    void HierarchicalUpdate() override;

    UFUNCTION(BlueprintCallable, Category="Vizor|RPC Requests|HelloService")
    bool Hello(FVizorDemonstration_HelloRequest Request, const FGrpcClientContext& Context);

    UFUNCTION(BlueprintCallable, Category="Vizor|RPC Requests|HelloService")
    bool ServerTime(FVizorDemonstration_ServerTimeRequest Request, const FGrpcClientContext& Context);
};


